name: Dizilla Günlük Güncelleme

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Çek
      uses: actions/checkout@v3

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Chrome ve Xvfb Kurulumu (Ekransız sunucuda tarayıcı çalıştırmak için)
    - name: Google Chrome ve Xvfb Kur
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable xvfb

    - name: Kütüphaneleri Yükle
      run: |
        pip install -r dizilla/requirements.txt

    - name: Scraper'ı Çalıştır (Sanal Ekran ile)
      run: |
        cd dizilla
        # xvfb-run komutu sahte bir monitör oluşturur
        xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" python main.py

    - name: Commit ve Push
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add dizilla/dizibox.m3u
        git diff --quiet && git diff --staged --quiet || (git commit -m "M3U Güncelleme" && git push)
